const admin = require("firebase-admin");
admin.initializeApp();
exports.signUpElderly = require("./signUpElderly");
exports.signUpVolunteer = require("./signUpVolunteer");
exports.tasks = require("./tasks");
exports.checkAccountType=require("./checkAccountType");
exports.stickers = require("./stickers");
exports.chats = require("./chats");
exports.advice = require("./advice");
exports.volunteerProfile = require("./volunteerProfile");